package com.miaosha.dao;

import com.miaosha.dataobject.DeptDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DeptDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_info
     *
     * @mbg.generated Wed Apr 17 09:01:58 CST 2019
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_info
     *
     * @mbg.generated Wed Apr 17 09:01:58 CST 2019
     */
    int insert(DeptDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_info
     *
     * @mbg.generated Wed Apr 17 09:01:58 CST 2019
     */
    int insertSelective(DeptDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_info
     *
     * @mbg.generated Wed Apr 17 09:01:58 CST 2019
     */
    DeptDO selectByPrimaryKey(Integer deptId);
    List<DeptDO> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_info
     *
     * @mbg.generated Wed Apr 17 09:01:58 CST 2019
     */
    int updateByPrimaryKeySelective(DeptDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_info
     *
     * @mbg.generated Wed Apr 17 09:01:58 CST 2019
     */
    int updateByPrimaryKey(DeptDO record);
}