package com.miaosha.dao;

import com.miaosha.dataobject.DrugOfStockOutTableDO;
import org.springframework.stereotype.Repository;

@Repository
public interface DrugOfStockOutTableDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_of_sot
     *
     * @mbg.generated Thu Apr 18 09:08:13 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_of_sot
     *
     * @mbg.generated Thu Apr 18 09:08:13 CST 2019
     */
    int insert(DrugOfStockOutTableDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_of_sot
     *
     * @mbg.generated Thu Apr 18 09:08:13 CST 2019
     */
    int insertSelective(DrugOfStockOutTableDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_of_sot
     *
     * @mbg.generated Thu Apr 18 09:08:13 CST 2019
     */
    DrugOfStockOutTableDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_of_sot
     *
     * @mbg.generated Thu Apr 18 09:08:13 CST 2019
     */
    int updateByPrimaryKeySelective(DrugOfStockOutTableDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_of_sot
     *
     * @mbg.generated Thu Apr 18 09:08:13 CST 2019
     */
    int updateByPrimaryKey(DrugOfStockOutTableDO record);
}