package com.miaosha.dao;

import com.miaosha.dataobject.DrugStockDO;

public interface DrugStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_stock
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    int deleteByPrimaryKey(Integer drugId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_stock
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    int insert(DrugStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_stock
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    int insertSelective(DrugStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_stock
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    DrugStockDO selectByPrimaryKey(Integer drugId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_stock
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    int updateByPrimaryKeySelective(DrugStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_stock
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    int updateByPrimaryKey(DrugStockDO record);
}