package com.miaosha.dao;

import com.miaosha.dataobject.DrugOfTableDO;
import org.springframework.stereotype.Component;

import java.util.List;

@Component

public interface DrugOfTableDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_of_table
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_of_table
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    int insert(DrugOfTableDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_of_table
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    int insertSelective(DrugOfTableDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_of_table
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    DrugOfTableDO selectByPrimaryKey(Integer id);

    List<DrugOfTableDO> selectByTableId(Integer tableId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_of_table
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    int updateByPrimaryKeySelective(DrugOfTableDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_of_table
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    int updateByPrimaryKey(DrugOfTableDO record);
}