package com.miaosha.dao;

import com.miaosha.dataobject.ItemDAO;
import com.miaosha.service.model.ItemModel;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface ItemDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Mar 29 09:04:43 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Mar 29 09:04:43 CST 2019
     */
    int insert(ItemDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Mar 29 09:04:43 CST 2019
     */
    int insertSelective(ItemDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Mar 29 09:04:43 CST 2019
     */
    ItemDAO selectByPrimaryKey(Integer id);

    List<ItemDAO> listItem();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Mar 29 09:04:43 CST 2019
     */
    int updateByPrimaryKeySelective(ItemDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Mar 29 09:04:43 CST 2019
     */
    int updateByPrimaryKey(ItemDAO record);
}