package com.miaosha.dao;

import com.miaosha.dataobject.SatDetailsDO;

public interface SatDetailsDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sat_details
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sat_details
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    int insert(SatDetailsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sat_details
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    int insertSelective(SatDetailsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sat_details
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    SatDetailsDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sat_details
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    int updateByPrimaryKeySelective(SatDetailsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sat_details
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    int updateByPrimaryKey(SatDetailsDO record);
}