package com.miaosha.dao;

import com.miaosha.dataobject.SatDO;

public interface SatDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_application_table
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_application_table
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    int insert(SatDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_application_table
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    int insertSelective(SatDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_application_table
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    SatDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_application_table
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    int updateByPrimaryKeySelective(SatDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_application_table
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    int updateByPrimaryKey(SatDO record);

    int countNums();
}