package com.miaosha.dao;

import com.miaosha.dataobject.SequenceInfoDAO;
import org.springframework.stereotype.Component;

@Component
public interface SequenceInfoDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Mar 29 16:39:33 CST 2019
     */
    int deleteByPrimaryKey(String name);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Mar 29 16:39:33 CST 2019
     */
    int insert(SequenceInfoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Mar 29 16:39:33 CST 2019
     */
    int insertSelective(SequenceInfoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Mar 29 16:39:33 CST 2019
     */
    SequenceInfoDAO selectByPrimaryKey(String name);

    SequenceInfoDAO getSequenceByName(String name);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Mar 29 16:39:33 CST 2019
     */
    int updateByPrimaryKeySelective(SequenceInfoDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Mar 29 16:39:33 CST 2019
     */
    int updateByPrimaryKey(SequenceInfoDAO record);
}