package com.miaosha.dao;

import com.miaosha.dataobject.UserPasswordDAO;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Component

public interface UserPasswordDAOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Mar 15 09:14:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Mar 15 09:14:20 CST 2019
     */
    int insert(UserPasswordDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Mar 15 09:14:20 CST 2019
     */
    int insertSelective(UserPasswordDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Mar 15 09:14:20 CST 2019
     */
    UserPasswordDAO selectByPrimaryKey(Integer id);
    UserPasswordDAO selectByUserId(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Mar 15 09:14:20 CST 2019
     */
    int updateByPrimaryKeySelective(UserPasswordDAO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Mar 15 09:14:20 CST 2019
     */
    int updateByPrimaryKey(UserPasswordDAO record);
}