package com.miaosha.dataobject;

public class DeptDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_info.dept_id
     *
     * @mbg.generated Wed Apr 17 09:01:58 CST 2019
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_info.name
     *
     * @mbg.generated Wed Apr 17 09:01:58 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_info.dept_id
     *
     * @return the value of dept_info.dept_id
     *
     * @mbg.generated Wed Apr 17 09:01:58 CST 2019
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_info.dept_id
     *
     * @param deptId the value for dept_info.dept_id
     *
     * @mbg.generated Wed Apr 17 09:01:58 CST 2019
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_info.name
     *
     * @return the value of dept_info.name
     *
     * @mbg.generated Wed Apr 17 09:01:58 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_info.name
     *
     * @param name the value for dept_info.name
     *
     * @mbg.generated Wed Apr 17 09:01:58 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}