package com.miaosha.dataobject;

public class DrugOfTableDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_of_table.id
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_of_table.medicine_table_id
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    private Integer medicineTableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_of_table.drug_id
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    private Integer drugId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_of_table.dose
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    private Integer dose;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_of_table.id
     *
     * @return the value of drug_of_table.id
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_of_table.id
     *
     * @param id the value for drug_of_table.id
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_of_table.medicine_table_id
     *
     * @return the value of drug_of_table.medicine_table_id
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    public Integer getMedicineTableId() {
        return medicineTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_of_table.medicine_table_id
     *
     * @param medicineTableId the value for drug_of_table.medicine_table_id
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    public void setMedicineTableId(Integer medicineTableId) {
        this.medicineTableId = medicineTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_of_table.drug_id
     *
     * @return the value of drug_of_table.drug_id
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    public Integer getDrugId() {
        return drugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_of_table.drug_id
     *
     * @param drugId the value for drug_of_table.drug_id
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    public void setDrugId(Integer drugId) {
        this.drugId = drugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_of_table.dose
     *
     * @return the value of drug_of_table.dose
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    public Integer getDose() {
        return dose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_of_table.dose
     *
     * @param dose the value for drug_of_table.dose
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    public void setDose(Integer dose) {
        this.dose = dose;
    }
}