package com.miaosha.dataobject;

import java.math.BigDecimal;

public class DrugDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.id
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.name
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.unit
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.description
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.price
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.id
     *
     * @return the value of drug.id
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.id
     *
     * @param id the value for drug.id
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.name
     *
     * @return the value of drug.name
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.name
     *
     * @param name the value for drug.name
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.unit
     *
     * @return the value of drug.unit
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.unit
     *
     * @param unit the value for drug.unit
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.description
     *
     * @return the value of drug.description
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.description
     *
     * @param description the value for drug.description
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.price
     *
     * @return the value of drug.price
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.price
     *
     * @param price the value for drug.price
     *
     * @mbg.generated Thu Apr 11 15:48:28 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}