package com.miaosha.dataobject;

public class DrugOfStockOutTableDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_of_sot.id
     *
     * @mbg.generated Thu Apr 18 09:08:13 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_of_sot.sot_id
     *
     * @mbg.generated Thu Apr 18 09:08:13 CST 2019
     */
    private Integer sotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_of_sot.drug_id
     *
     * @mbg.generated Thu Apr 18 09:08:13 CST 2019
     */
    private Integer drugId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_of_sot.num
     *
     * @mbg.generated Thu Apr 18 09:08:13 CST 2019
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_of_sot.id
     *
     * @return the value of drug_of_sot.id
     *
     * @mbg.generated Thu Apr 18 09:08:13 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_of_sot.id
     *
     * @param id the value for drug_of_sot.id
     *
     * @mbg.generated Thu Apr 18 09:08:13 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_of_sot.sot_id
     *
     * @return the value of drug_of_sot.sot_id
     *
     * @mbg.generated Thu Apr 18 09:08:13 CST 2019
     */
    public Integer getSotId() {
        return sotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_of_sot.sot_id
     *
     * @param sotId the value for drug_of_sot.sot_id
     *
     * @mbg.generated Thu Apr 18 09:08:13 CST 2019
     */
    public void setSotId(Integer sotId) {
        this.sotId = sotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_of_sot.drug_id
     *
     * @return the value of drug_of_sot.drug_id
     *
     * @mbg.generated Thu Apr 18 09:08:13 CST 2019
     */
    public Integer getDrugId() {
        return drugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_of_sot.drug_id
     *
     * @param drugId the value for drug_of_sot.drug_id
     *
     * @mbg.generated Thu Apr 18 09:08:13 CST 2019
     */
    public void setDrugId(Integer drugId) {
        this.drugId = drugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_of_sot.num
     *
     * @return the value of drug_of_sot.num
     *
     * @mbg.generated Thu Apr 18 09:08:13 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_of_sot.num
     *
     * @param num the value for drug_of_sot.num
     *
     * @mbg.generated Thu Apr 18 09:08:13 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}