package com.miaosha.dataobject;

public class DrugStockDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_stock.drug_id
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    private Integer drugId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_stock.stock
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    private Integer stock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_stock.drug_id
     *
     * @return the value of drug_stock.drug_id
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    public Integer getDrugId() {
        return drugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_stock.drug_id
     *
     * @param drugId the value for drug_stock.drug_id
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    public void setDrugId(Integer drugId) {
        this.drugId = drugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_stock.stock
     *
     * @return the value of drug_stock.stock
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_stock.stock
     *
     * @param stock the value for drug_stock.stock
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }
}