package com.miaosha.dataobject;

import java.util.Date;

public class ProcessedMedicineTableDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column processed_medicine_table.id
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column processed_medicine_table.medical_order_id
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    private Integer medicalOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column processed_medicine_table.account_id
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column processed_medicine_table.add_time
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column processed_medicine_table.id
     *
     * @return the value of processed_medicine_table.id
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column processed_medicine_table.id
     *
     * @param id the value for processed_medicine_table.id
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column processed_medicine_table.medical_order_id
     *
     * @return the value of processed_medicine_table.medical_order_id
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    public Integer getMedicalOrderId() {
        return medicalOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column processed_medicine_table.medical_order_id
     *
     * @param medicalOrderId the value for processed_medicine_table.medical_order_id
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    public void setMedicalOrderId(Integer medicalOrderId) {
        this.medicalOrderId = medicalOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column processed_medicine_table.account_id
     *
     * @return the value of processed_medicine_table.account_id
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column processed_medicine_table.account_id
     *
     * @param accountId the value for processed_medicine_table.account_id
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column processed_medicine_table.add_time
     *
     * @return the value of processed_medicine_table.add_time
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column processed_medicine_table.add_time
     *
     * @param addTime the value for processed_medicine_table.add_time
     *
     * @mbg.generated Tue Apr 16 16:36:29 CST 2019
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}