package com.miaosha.dataobject;

public class SatDetailsDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sat_details.sat_id
     *
     * @mbg.generated Thu Apr 18 14:31:16 CST 2019
     */
    private Integer satId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sat_details.drug_id
     *
     * @mbg.generated Thu Apr 18 14:31:16 CST 2019
     */
    private Integer drugId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sat_details.sat_id
     *
     * @return the value of sat_details.sat_id
     *
     * @mbg.generated Thu Apr 18 14:31:16 CST 2019
     */
    public Integer getSatId() {
        return satId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sat_details.sat_id
     *
     * @param satId the value for sat_details.sat_id
     *
     * @mbg.generated Thu Apr 18 14:31:16 CST 2019
     */
    public void setSatId(Integer satId) {
        this.satId = satId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sat_details.drug_id
     *
     * @return the value of sat_details.drug_id
     *
     * @mbg.generated Thu Apr 18 14:31:16 CST 2019
     */
    public Integer getDrugId() {
        return drugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sat_details.drug_id
     *
     * @param drugId the value for sat_details.drug_id
     *
     * @mbg.generated Thu Apr 18 14:31:16 CST 2019
     */
    public void setDrugId(Integer drugId) {
        this.drugId = drugId;
    }
}