package com.miaosha.dataobject;

public class SatDetailsDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sat_details.id
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sat_details.drug_id
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    private Integer drugId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sat_details.num
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sat_details.sat_id
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    private Integer satId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sat_details.id
     *
     * @return the value of sat_details.id
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sat_details.id
     *
     * @param id the value for sat_details.id
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sat_details.drug_id
     *
     * @return the value of sat_details.drug_id
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    public Integer getDrugId() {
        return drugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sat_details.drug_id
     *
     * @param drugId the value for sat_details.drug_id
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    public void setDrugId(Integer drugId) {
        this.drugId = drugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sat_details.num
     *
     * @return the value of sat_details.num
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sat_details.num
     *
     * @param num the value for sat_details.num
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sat_details.sat_id
     *
     * @return the value of sat_details.sat_id
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    public Integer getSatId() {
        return satId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sat_details.sat_id
     *
     * @param satId the value for sat_details.sat_id
     *
     * @mbg.generated Wed Apr 17 14:41:43 CST 2019
     */
    public void setSatId(Integer satId) {
        this.satId = satId;
    }
}